# Parameters for your particle filter

motion_params:
  vel_std:    0.03
  delta_std:  0.1
  x_std:      0.02
  y_std:      0.01
  theta_std:  0.02

sensor_params:
  hit_std:    0.3
  z_hit:      0.4
  z_short:    0.03
  z_max:      0.04
  z_rand:     0.2