# Parameters for your particle filter

motion_params:
  vel_std:    0.03
  delta_std:  0.2
  x_std:      0.03
  y_std:      0.02
  theta_std:  0.03

sensor_params:
  hit_std:    0.5
  z_hit:      0.4
  z_short:    0.05
  z_max:      0.02
  z_rand:     0.4
